[package]
name = "astero-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
crossterm = { version = "0.29", default-features = false, features = ["windows"] }
astero-core = { path = "../astero-core" }
astero-debug = { path = "../astero-debug" }

[dev-dependencies]
astero-loader = { path = "../astero-loader" }
